### ISSUE TITLE
SSG-Dataset Confusion

### ISSUE THREAD

**Issue by gauravsh0812** [CAMMA-public/SSG-VQA#2]
Hi there!
I am a PhD student collaborating with Dr. E.J. Lee at The University of Arizona. I recently came across your work on SSG-VQA and found it incredibly fascinating. I am eager to explore and potentially contribute to this project.
As I dug deeper into the documentation, I encountered some initial confusion. According to the documentation, the dataset is expected to include Question-Answer pairs, along with features for Regions of Interest (RoI) and Cropped images sourced from the cholec80 dataset. Could you kindly guide how I can access the images that were utilized as samples in the dataset?
Your assistance in this matter would be greatly appreciated.

Thank you!

**Comment by Flaick** [comment]
Hello, thank you for the interest. In this repo, we are providing the processed feature vector for each surgical scene image. But if you want to start from the scratch, here are the steps. 
1. Download CholecT45 dataset from https://github.com/CAMMA-public/cholect50/blob/master/docs/README-Downloads.md
    We use the images from this dataset to build our training and testing set.
2. Use the feature extraction files under utils folder to generate the feature vectors for images.
    a. feat_extract_visual.py --> resnet visual feature vectors
    b. feature_extract_roi.py --> resnet visual feature vectors + scene-aware vectors. In this case, you will need scene graphs as additional input. The scene graph we are using will be provided soon.

**Comment by Feng-Sir0** [comment]
Hello!
That's a great work!  I am very interested in your research. While exploring your paper and project, I noticed that the **Scene Graph Generation** part of the pipeline in Fig. 3 ("Pipeline of the SSG-VQA-Net") from your paper "Advancing Surgical VQA with Scene Graph Knowledge" is not included in the code provided in this repository.
I am eager to learn more about your work and would greatly appreciate it if you could share the code for this part of the pipeline.

Looking forward to your response.

Thank you!
